### ISSUE TITLE
(BSC) Normal send funds transaction is inaccurate

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#149] opened 2023-02-23 04:42 UTC
### Issue Category

Other

### What happened?

When user performs a normal send transaction - sends 100 DAOD from  his safe to another address, recipient does not receive the 100 DAOD but instead received 98 DAOD
![image](https://user-images.githubusercontent.com/114049495/220822747-7874f66f-4222-4204-9737-c6d9ed8cc74a.png)
![image](https://user-images.githubusercontent.com/114049495/220822795-54033f9f-77a1-4288-8de6-ffffc93005d6.png)

### Date and time this happened or you first noticed this issue

23-02-2023 06:42

### Network

Binance Smart Chain

### Safe Address

0x3B6B4B1aD2CEc3e8b679238CAcd6daC92621cc8A

### Token Type

None

### Transactions

```shell
https://bscscan.com/tx/0x3e428f1505076b1bdbcbfec188936338625cb523315c6985ef037d94aa8e0768
```

**Comment by schmanu** [comment] 2023-02-23 08:27
I checked the contracts transfer function and it apparently takes a fee on every transfer.

**Comment by inahlikenoother** [comment] 2023-02-23 10:10
Thank you @schmanu, is this like a transaction fee when doing a transfer from user's safe?

**Comment by ennisjo** [comment] 2023-02-24 16:07
@schmanu - is it a transaction fee interacting with the token contract of DAOD?

**Comment by schmanu** [comment] 2023-02-24 16:51
@ennisjo Yes exactly.

If you look at https://bscscan.com/token/0x37fd1a01dc5615e27300cfaf52d37b3b9bbc626c#code and especially the `_transferStandard` function it does some computations to calculate three fees:
- charityFee
- liquidityFee
- taxFee

And it deducts those 3 fees from the transferred amount:
```solidity
    function _transferStandard(
        address sender,
        address recipient,
        uint256 tAmount
    ) private {
        (
            uint256 rAmount,
            uint256 rTransferAmount,
            uint256 rFee,
            uint256 tTransferAmount,
            uint256 tFee,
            uint256 tLiquidity,
            uint256 tCharity
        ) = _getValues(tAmount);
        _rOwned[sender] = _rOwned[sender].sub(rAmount);
        _rOwned[recipient] = _rOwned[recipient].add(rTransferAmount);
        _takeLiquidity(tLiquidity);
        _takeCharityFee(tCharity);
        _reflectFee(rFee, tFee);
        emit Transfer(sender, recipient, tTransferAmount);
    }
```

**Comment by ennisjo** [comment] 2023-02-27 16:46
@inahlikenoother - let's close this issue then if the issue is related to the token contract creator.

**Closed** 2023-02-27 23:01 UTC
Labels: other, bsc
