### ISSUE TITLE
[Android] Error 422422 Failed to create transaction: network request failed with an unexpected error, Gnosis Chain

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#388] opened 2024-02-19 11:00 UTC
### Issue Category

Transaction missing / not visible in app or service

### What happened?

User was trying to transfer token using the safe mobile app (Android) but getting 422422 error while initiating the transaction [clicking the review button]. (No issue using the web app via PC)

Safe address: https://app.safe.global/home?safe=gno:0xC70B2F561E136F8BF42A26B426c3a89D7a44875e

More details:
Device: Samsung galaxy s23 ultra
Device OS: Android 14
Safe mobile app version 3.9.0
Owner wallet: Tried Ledger nano x and keystone 3 pro (both are getting the same error):

![image](https://github.com/5afe/safe-support/assets/114005210/2de6a13e-bfa5-44e1-a2ca-9ac4d29f476f)

### Date and time this happened or you first noticed this issue

19-02-2024

### Network

Gnosis Chain

### Safe Address

gno:0xC70B2F561E136F8BF42A26B426c3a89D7a44875e

### Token Type

None

**Comment by liliya-soroka** [comment] 2024-02-27 11:07
checking ...

**Comment by Claire-serveth** [comment] 2024-02-27 11:10
> checking ...

Thank you @liliya-soroka 🙏

**Comment by liliya-soroka** [comment] 2024-02-27 12:05
Reported to the android repo - https://github.com/safe-global/safe-android/issues/2018
I was able to reproduce it. For me it happens for the EURe transfer ( no issue with other tokens)
The issue is reported but there is no timeline for when it will be fixed as the android app is onhold

**Comment by Claire-serveth** [comment] 2024-02-27 13:50
> Reported to the android repo - [safe-global/safe-android#2018](https://github.com/safe-global/safe-android/issues/2018) I was able to reproduce it. For me it happens for the EURe transfer ( no issue with other tokens) The issue is reported but there is no timeline for when it will be fixed as the android app is onhold

Will let the user know, thank you so much @liliya-soroka 🙏

**Closed** 2024-02-27 13:57 UTC
