### ISSUE TITLE
Failed to create transaction: The data couldn't be read because it isn't in the correct format. Error 1300

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#326] opened 2023-11-19 00:06 UTC
### Issue Category

Other

### What happened?

User gets the error when trying to sign a vote transaction in the IOS web app 

IOS 17.0
App version: v3.24.0
Dapp URL:  https://www.nouns.camp/ and https://www.nouns.wtf/

- User has no issues with pairing the app with walletconnect
- Issue occurs when trying to initially vote / create the transaction
- No issue occurs when trying to create and execute through the web app. Issue only occurs with the mobile app
![image](https://github.com/5afe/safe-support/assets/114544040/2b65d1d4-c1cd-4d30-9c6e-0661ceb244a8)

### Date and time this happened or you first noticed this issue

19/11/2023

### Network

Ethereum Mainnet

### Safe Address

0xcC2688350d29623E2A0844Cc8885F9050F0f6Ed5

### Token Type

None

**Comment by katspaugh** [comment] 2023-12-20 12:22
A sidebote: it would be great to keep prepending ticket titles with `[iOS]`, `[Android]`, super useful for us.

**Comment by liliya-soroka** [comment] 2023-12-20 15:21
Could you re-check with the user , please?
Our infra team released the fix today

**Comment by liliya-soroka** [comment] 2024-01-22 13:53
Please, re-check the issue with the user. The issue should be fixed

**Comment by Claire-serveth** [comment] 2024-01-29 09:34
I can't find the ticket anymore, so it seems the issue is fixed on user's end. Thank you @liliya-soroka 🙏

**Closed by Claire-serveth** 2024-01-29 09:34 UTC
