### ISSUE TITLE
Some users cannot load safes in BSC for both webapp and iOS app

### ISSUE THREAD

**Issue by phoebe-serveth** [5afe/safe-support#105] opened 2022-12-26 17:00 UTC
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Cannot load safes in BSC using webapp and iOS app.
Getting this error on console:
![image](https://user-images.githubusercontent.com/114040259/209569707-019252b5-f398-4fcf-b550-06eefd9badd3.png)

This error on iOS:
![image](https://user-images.githubusercontent.com/114040259/209569843-b9c110be-afac-4497-9d2e-45d2099ec1b4.png)

### Date and time this happened or you first noticed this issue

26-12-2022 12:57AM

### Network

Binance Smart Chain

### Safe Address

0xdf0048DF98A749ED36553788B4b449eA7a7BAA88

### Token Type

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Claire-serveth** [comment] 2022-12-26 19:04
I have users having issues with their safes for BSC as well. Users can't confirm transactions. Safe addresses:
0xc3dD47c5bdb837071E41Ee067cF2de25c968e625
0x38265ca92C4cB89648A42842CFD17920f0e3da03
0x8B43aaCE38f536f21698AC2C3969FA4F64563f35

![image](https://user-images.githubusercontent.com/114005210/209577000-4bafac60-9a7d-4178-b488-73959b4f305c.png)

**Comment by Sherie15** [comment] 2022-12-27 06:45
Same issue with the user.

Safe address bnb:0x21835332cBDf1b3530fAE9f6Cd66FEB9477dFC02
Browser: Chrome/Firefox

https://gnosis-safe.io/app/bnb:0x21835332cBDf1b3530fAE9f6Cd66FEB9477dFC02/transactions/queue
![image](https://user-images.githubusercontent.com/113986185/209623606-a6131bf3-c98f-45d8-86b5-7f2747600569.png)

https://app.safe.global/bnb:0x21835332cBDf1b3530fAE9f6Cd66FEB9477dFC02/transactions/history
![image](https://user-images.githubusercontent.com/113986185/209623659-b7840a9b-8546-46d8-b0bf-781f1f45db5f.png)

**Comment by JagoFigueroa** [comment] 2022-12-27 07:12
Thank you for reporting! The team is on it, I will let you guys know 😄

**Comment by JagoFigueroa** [comment] 2022-12-27 08:53
Issue should be now resolved 😎

**Comment by leekinwai** [comment] 2022-12-27 10:05
What is the root cause?

**Comment by JagoFigueroa** [comment] 2022-12-27 10:29
database related issues 👍

**Comment by JagoFigueroa** [comment] 2022-12-27 16:12
I will go ahead and close this ticket as I can see all of the shared safes loading + with transactions from today 😄 

Cheers!

**Closed by JagoFigueroa** 2022-12-27 16:12 UTC
Labels: safe_loading, bsc
