### ISSUE TITLE
[ARB] Balance not updating/moving between wallets despite the transaction showing as successful

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#364] opened 2024-01-04 00:37 UTC
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User successfully sent two transactions 0.035 ETH each even though their initial balance was only 0.035 ETH.
https://app.safe.global/transactions/history?safe=arb1:0xAB487ac3D49a39FD4927d8381736Ea51da4b7a51
![image](https://github.com/5afe/safe-support/assets/114049668/04b2d74b-ced6-45f3-a8e3-f52ecc80af95)

Transaction was showing as successful but safe balance was not deducted:
- Safe UI
![image](https://github.com/5afe/safe-support/assets/114049668/44c64964-81e7-44b7-b2b2-f79cff0ada70)

- Arbiscan
![image](https://github.com/5afe/safe-support/assets/114049668/f1d46481-69f0-417a-8140-9e99e8557b62)

First transaction:
https://arbiscan.io/tx/0x3e8312339142b301e4e17aa5852d78911983aa53af33dcfe0ef837ec69b044cc
State change (no difference)
![image](https://github.com/5afe/safe-support/assets/114049668/9ae4d249-4bda-42d0-9c45-4079b4d09eae)

Second transaction:
https://arbiscan.io/tx/0xecf71fcc5a208ca5622eca4b05b9b8579e917ae3fab38afb50aeb741813c642b
State change (no difference)
![image](https://github.com/5afe/safe-support/assets/114049668/8c22305c-97fd-4b47-bc31-d1bdca905c12)

Receiving wallet:
https://arbiscan.io/address/0xC803223a8120AC77ee9694a11d42E0207987b4f9#internaltx
![image](https://github.com/5afe/safe-support/assets/114049668/2b4b1f4b-dfc0-404f-826b-378cc9b1e563)

### Date and time this happened or you first noticed this issue

04-01-2024

### Network

Arbitrum

### Safe Address

0xAB487ac3D49a39FD4927d8381736Ea51da4b7a51

### Token Type

None

**Comment by joanpan** [comment] 2024-01-04 04:41
The user was able to initiate another transaction, and it looks like the safe balance got deducted now. Not sure why the first two transactions went through fine without deducting anything

https://arbiscan.io/tx/0xb232928dd989da17f7248db724d14b743269397ac9a0336e5bb780c3386c349a 
![image](https://github.com/5afe/safe-support/assets/114049668/372b611d-78c3-477d-b984-6d31f6e726e2)

**Comment by JagoFigueroa** [comment] 2024-01-04 08:06
Hi there! Looks like a temporary issue during this evening. I have tried with a couple of my test safes on arbitrum and balances look to be updating as expected as well now so I will go ahead and close this if that is okay.

Cheers!

**Comment by MicahZoltu** [comment] 2024-01-04 10:34
@JagoFigueroa What sort of temporary issue would result in the UI attaching ETH to SAFE transactions that are supposed to be sending ETH?  Is this something where the user can accidentally attach ETH to a SAFE transaction?

**Comment by JagoFigueroa** [comment] 2024-01-04 11:24
My bad there, was a bit too quick to reach a conclusion given some issues that we had this evening on our end, reopened it 😅 

I am checking with the devs, we will post more details on what we think happened shortly 😄

**Comment by DaniSomoza** [comment] 2024-01-04 11:28
The issue you're encountering with the those Safe transaction involves the `execTransaction` method. Specifically, a user is attempting to transfer `0.035 ETH` to the same EOA that is initiating the transaction. However, the problem arises because the transaction executing the `execTransaction` method has a value set to the same amount of `0.035 ETH`, when ideally, it should be zero.

As a result, although the transaction completes successfully, the resulting balance remains unchanged. **This is because, on one hand, you are sending out ETH, and on the other, the same amount is being returned to the account.** 

 This can be confusing as it appears as a successful transaction, yet the account balance does not reflect the expected decrease from sending ETH.
 
 In the first 2 transactions yo can see the `value` field set as `0.035 ETH`:
 ```
 https://arbiscan.io/tx/0x3e8312339142b301e4e17aa5852d78911983aa53af33dcfe0ef837ec69b044cc
 ```
![Captura de pantalla 2024-01-04 a las 12 19 56](https://github.com/5afe/safe-support/assets/26763673/bbfedf1c-96dc-47af-a1b8-2de89bd012ef)


And in the last transaction the value is correctly set to 0:
```
https://arbiscan.io/tx/0xb232928dd989da17f7248db724d14b743269397ac9a0336e5bb780c3386c349a
```
![Captura de pantalla 2024-01-04 a las 12 27 22](https://github.com/5afe/safe-support/assets/26763673/59037760-a803-4377-9a4b-0aa1745bd600)

**Comment by MicahZoltu** [comment] 2024-01-04 11:38
@DaniSomoza That is the same conclusion I came to, but what is confusing to me is how the user managed to construct such a transaction through the SAFE UI?

**Comment by DaniSomoza** [comment] 2024-01-04 11:57
@MicahZoltu, that's a good question.

I attempted to reproduce the issue using the Safe UI, but everything worked fine on my end.

Is it possible that the user is not utilizing the Safe UI to build this transaction? Could they be using a custom script instead?

**Comment by JagoFigueroa** [comment] 2024-01-08 08:32
We will share this with the mobile team. Thanks @CindyLo0!

**Comment by Claire-serveth** [comment] 2024-10-09 16:08
Sorry, I have to close this issue to find the intercom ticket: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700005123?view=List

**Closed** 2024-10-09 16:07 UTC
