### ISSUE TITLE
[BSC chain]Transaction does not post in Transaction Queue after submitting/signing

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#15] opened 2022-09-26 18:47 UTC
### Issue Category

Transaction execution issue

### What happened?

> Issue: Transaction does not post in transaction queue after submitting/signing
> Transaction type: Transfer/send to defi wallet
> Issue applies to ALL owners
> Simulate transaction throws "Error 403"
> Owners get a confirm transaction statement, but then nothing posts.

### Date and time this happened or you first noticed this issue

27-09-2022

### Network

Binance Smart Chain

### Safe Address

0x4aBA7742B54DC89Fa03220299fD2550F9828a7aD

### Token Address

0xe9e7cea3dedca5984780bafc599bd69add087d56

### Token Type

ERC20

### Transactions

```shell
N/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joanpan** [comment] 2022-09-26 21:59
Another user reported similar issue.
Safe address: bnb:0x714872BD713984a67384Ee6e60414ADF1f2F62d5 

![image](https://user-images.githubusercontent.com/114049668/192388180-bc15fa98-6ab7-44fb-9016-92bf190f9b5a.png)

**Comment by joanpan** [comment] 2022-09-27 00:47
Another user with a similar issue. Cannot execute transaction on both desktop and iOS.
Safe address: bnb:0x9352e125c65FC0Ed210E9aA612EcB22B94878353

Stuck pending:
![image](https://user-images.githubusercontent.com/114049668/192405938-378f441b-a6a2-412c-a508-bdcb532a9f46.png)

Error on iOS: 
An SSL error has occurred and a secure connection to the server cannot be made

**Comment by med3000** [comment] 2022-09-29 13:35
hi @joanpan is this still an issue? It was happening around the time there were some issues with bsc

**Comment by joanpan** [comment] 2022-09-30 19:39
No updates from the users yet

**Comment by med3000** [comment] 2022-10-05 07:41
hi @joanpan will close this ticket off since no further news from the user and we're unable to reproduce this. thanks

**Closed by med3000** 2022-10-05 07:41 UTC
Labels: tx_execution
