### ISSUE TITLE
Can't initiate transactions from Ledger Nano X - Error: The Safe SDK could not be initialized

### ISSUE THREAD

**Issue by bingclo** [5afe/safe-support#408] opened 2024-03-19 17:28 UTC
### Issue Category

Transaction execution issue

### What happened?

User is trying to do a simple ETH send transaction in the interface but confirm button is greyed out with this error: 
`The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up error while initiating transaction`

![image](https://github.com/5afe/safe-support/assets/54754746/9b551c45-2c8f-441e-9f27-81349de85288)
![image](https://github.com/5afe/safe-support/assets/54754746/6b9ee7b5-4db4-4d28-a618-af1d2ad09a2c)

User already tried connecting directly and using Metamask, cleared cache and cookies and using other USB ports. 
All other owner wallets work fine. 

What could cause this issue? 

### Date and time this happened or you first noticed this issue

19/03/2024 19:20:54

### Network

Ethereum Mainnet

### Safe Address

https://app.safe.global/settings/setup?safe=eth:0xFF54c5c8F32b2c8444B765c836172809108f0702

### Token Address

N/A (ETH)

### Token Type

None

### Transactions

```shell
N/A
```

**Comment by Claire-serveth** [comment] 2024-04-02 14:26
Update from user: the issue is still persistent

**Comment by Claire-serveth** [comment] 2024-05-05 10:44
User was unresponsive, intercom ticket was closed, so I'm closing this issue now.

**Closed by Claire-serveth** 2024-05-05 10:44 UTC
Labels: mainnet
