### ISSUE TITLE
[Android Safe app] App crashes as soon as it sees the QR code generated by AirGap Vault

### ISSUE THREAD

**Issue by la1234512345** [5afe/safe-support#423] opened 2024-04-02 03:57 UTC
### Issue Category

Other

### What happened?

When scanning QR code for AirGap Vault wallet, the app crashes/closes

Steps to reproduce the issue
1. Go to Settings > Owner Keys
2. Choose Add > "Connect to Keystone"
3. Scan the AirGap Vault QR
4. App closes

User is using the Keystone option as AirGap Vault is supposedly to work using the keystone flow. On the web UI, using Keystone option works for this wallet.

App/Device details:
Safe mobile app - 3.9.0
AirGap Vault - 3.26.0
Google Pixel 8

### Date and time this happened or you first noticed this issue

02-04-2024

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment] 2024-05-27 10:16
The issue might be related to the https://github.com/safe-global/safe-android/issues/2030 problem with keystone key QR code scanning we had

**Comment by DmitryBespalov** [comment] 2024-05-27 10:35
This one is a duplicate of the safe-global/safe-android#2030 @liliya-soroka @la1234512345

**Comment by liliya-soroka** [comment] 2024-08-05 13:36
could you ask the user to re-check? The fix for the keystone QR code was released

**Comment by Claire-serveth** [comment] 2024-08-05 14:25
Thank you @liliya-soroka the ticket might be closed already but will close this issue for now and reopen should there be a need. 🙏

**Closed by Claire-serveth** 2024-08-05 14:25 UTC
