### ISSUE TITLE
User is getting this error when creating a new safe

### ISSUE THREAD

**Issue by jakekvm01** [5afe/safe-support#107] opened 2022-12-27 14:57 UTC
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User is getting this error when creating a new safe.
Already done basic troubleshooting. Also tried different browsers.
https://app.intercom.com/a/inbox/km54f6ih/inbox/admin/5149131/conversation/36000021486?view=List

![image](https://user-images.githubusercontent.com/105864754/209683170-9e523075-9ec7-4581-8d3c-88a241e31bbd.png)

![image](https://user-images.githubusercontent.com/105864754/209683059-2fca7a7a-efa6-4b6d-84d7-27b98c17bf17.png)

### Date and time this happened or you first noticed this issue

12 hours ago

### Network

Ethereum Mainnet

### Safe Address

N/A

### Token Address

N/A

### Token Type

None

### Transactions

```shell
https://app.intercom.com/a/inbox/km54f6ih/inbox/admin/5149131/conversation/36000021486?view=List and https://app.intercom.com/a/inbox/km54f6ih/inbox/shared/all/conversation/36000021483?view=List
```

Discord: https://discord.com/channels/907968493134155807/915922168846618674/1057306996195467274

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JagoFigueroa** [comment] 2022-12-27 15:48
Unfortunately I am not able to reproduce this. Any relevant steps or info that could help us do so? 

On the shared screenshots I can see that no chain or wallet are being loaded for the user which would explain why creation or safes being loaded is not possible to begin with but I wonder how the user reached that state. 

Is the user using some tool like a VPN that might we blocking requests on the network tab?

**Comment by erisonmeira** [comment] 2022-12-27 22:01
@JagoFigueroa
Yes, I use opensea, sudoswap, uniswap and any other application with the normal metamask, when entering the website gnosis safe app the button "connect" does not work, and this is the error that appears in the console in any browser.

My metamask does not open.
Thanks, i am user!

**Comment by erisonmeira** [comment] 2022-12-28 00:59
Oh just now I did the test with vpn and it released access, why is my ip being blocked?
I have a dedicated ip, I reset the modem but it still doesn't work, only with vpn in the same country it works.

**Comment by JagoFigueroa** [comment] 2022-12-28 07:22
We think it may be internet provider related, blocking traffic to our site 😞 

Happy to read that you were able to work around this with a VPN @erisonmeira . I will pass this info to the team and close this ticket if that is ok. We will keep researching if there is something we can do from our side.

Thanks! 😄

**Closed by JagoFigueroa** 2022-12-28 07:22 UTC
Labels: mainnet, safe_loading
