### ISSUE TITLE
500 Error with Optimism TXS

### ISSUE THREAD

**Issue by DefiDebauchery** [5afe/safe-support#315] opened 2023-10-26 18:22 UTC
### Issue Category

Transaction execution issue

### What happened?

I'm trying to post a simple transaction through the Optimism Transaction Service, but encountering HTTP 500 errors.

I don't believe this is an error on my side, because if there was a data issue, it should be a 400/422, and I've been able to submit native tokens in this way for quite a while.

The only thing I can point to is either something specific to Op, or the recent TXS upgrade to 4.27.x.
Exact payload here (active for as long as this issue is) - https://gist.github.com/DefiDebauchery/3e9428601146af3975c10121c1b43b9f

### Date and time this happened or you first noticed this issue

26-10-2023 17:00

### Network

Optimism

### Safe Address

0x4ABa01FB8E1f6BFE80c56Deb367f19F35Df0f4aE

### Token Type

None

**Comment by JagoFigueroa** [comment] 2023-10-27 07:05
Good morning @DefiDebauchery! I was trying to reproduce this on my end with a safe with the same version as yours but transactions are going though for me. Could you recheck in case it was a temporary issue yesterday?

Cheers!

**Comment by mmv08** [comment] 2023-10-27 07:52
> Good morning @DefiDebauchery! I was trying to reproduce this on my end with a safe with the same version as yours on optimism but transactions are going though for me. Could you recheck in case it was a temporary issue yesterday?
> 
> Cheers!

I've looked into the issue with @fmrsabino, and we could reproduce it for payloads larger than 100kbs (the payload in the attached gist is around 150kb). So, the catch here is not the safe version but a large payload. I'm curious if the infra team made any fixes, so it's worth checking with them.

**Comment by mmv08** [comment] 2023-10-27 09:35
I mixed up the issues, and it's a different one. Sorry gents 🙈

**Comment by sajanrajdev** [comment] 2023-10-27 17:00
I have been encountering the same issue (`Server Error (500)`) since yesterday but when attempting to post to Safes on Ethereum Mainnet and Arbitrum. I have attempted with large/complex transactions and as well as simpler/lighter ones, the error remains the same.

Here are the latest payloads attempted:
[Ethereum](https://gist.github.com/sajanrajdev/962bf7735549780c60d4964fd1e868bb)
[Arbitrum](https://gist.github.com/sajanrajdev/ef2108546d66c64894e9008451b87244)

**Comment by DefiDebauchery** [comment] 2023-10-29 14:42
I'm also getting this behavior on Polygon. I haven't tested all networks provided by Safe Global, but I'm guessing something happened to the transaction-service or the infrastructure in front of it.

It isn't a code issue, as self-hosted environments from other EVM chains continue to work just fine with whatever versions of the TXS they are running.

Errors:
- Polygon
- Optimism
- Arbitrum

Working as intended:
- Base
- Ethereum (I was not able to replicate @sajanrajdev's issue on this chain)

Will continue to test as I can.

**Comment by DefiDebauchery** [comment] 2023-10-29 14:58
I don't know if it is related, but I also had trouble adding transactions from the Safe UI for Polygon. Looked like it had gotten a generic "we can't execute this request" from the connected RPC. After a few retries, it went through.

**Comment by mmv08** [comment] 2023-10-29 21:26
Also reported here https://ethereum.stackexchange.com/questions/155912/server-error-500-when-attempting-to-post-a-transaction-from-brownie-apesafe

**Comment by Uxio0** [comment] 2023-10-31 16:32
This should be fixed now on production

**Closed by Uxio0** 2023-10-31 16:32 UTC
Labels: tx_execution
