### ISSUE TITLE
[BSC] The Safe SDK could not be initialized

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#380] opened 2024-02-02 16:21 UTC
### Issue Category

Other

### What happened?

1. User was able to submit transaction using owner 1
2. Connected owner2 to the Safe, has an option to create New transaction but sign/confirm button is greyed out for transactions on Queue. (see screenshot) 
![image](https://github.com/5afe/safe-support/assets/79137197/9d6e8e1a-b1a9-4f16-b11d-a81893f03143)
3. Switched wallet to owner 2 and tried to submit transaction but getting the error shown in the screenshot: 
![image](https://github.com/5afe/safe-support/assets/79137197/0b2b3e75-8c4a-439c-9dc7-6b7416555aae)
4. Used an impersonator but cannot replicate on my end however, user shared a video recording: 
https://drive.google.com/file/d/1rAyUoeFtzyJSXblgbepKcoUhcjAgml72/view?usp=sharing

### Date and time this happened or you first noticed this issue

02-02-2024 18:00

### Network

Binance Smart Chain

### Safe Address

0xA8EA30B61cc488fc39d0521EDd947d9363994d96

### Token Type

None

**Comment by liliya-soroka** [comment] 2024-02-27 13:29
Could you re-check with the user if the issue is still relevant?

**Comment by Claire-serveth** [comment] 2024-02-27 14:00
Hi @liliya-soroka checking with the users for now. 🙏

**Comment by Claire-serveth** [comment] 2024-02-27 18:52
> Could you re-check with the user if the issue is still relevant?

I haven't got a response from the user yet, but looking at his safe address, it seems the issue still persists since pending transactions are still lacking 1 more confirmation: 
![image](https://github.com/5afe/safe-support/assets/114005210/1af314eb-5f31-4bab-adda-107ae93fbdfb)

**Comment by Claire-serveth** [comment] 2024-03-11 08:21
User was able to execute transactions successfully already, so I'm closing this issue now. 🙏

**Closed by Claire-serveth** 2024-03-11 08:21 UTC
