### ISSUE TITLE
[BSC] Error connecting to the blockchain

### ISSUE THREAD

**Issue by joanpan** [5afe/safe-support#493] opened 2024-07-22 22:44 UTC
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

The user repeatedly encounters an "error connecting to the blockchain." This error appears when they reload the page. 
<img width="1440" alt="image-1" src="https://github.com/user-attachments/assets/0da64d7b-0f76-4649-9f6e-cadb1cef0329">

They also receive this error when attempting to initiate a transaction (add signer). 
![image](https://github.com/user-attachments/assets/4b2f2847-dbf0-4110-b4b8-1cc72781cc19)

Console: 
<img width="1438" alt="image-1" src="https://github.com/user-attachments/assets/5527c007-037f-4088-b282-3a79a6f10d59">

They have tried multiple browsers, different internet connections, and different RPCs, but the issue persists. User is not using any VPN.

### Date and time this happened or you first noticed this issue

23-07-2024

### Network

Binance Smart Chain

### Safe Address

0x028e73a693954Df6214120246Fe9fea030e8d5f4

### Token Type

None

**Comment by liliya-soroka** [comment] 2024-08-05 12:13
could you check if the issue is still relevant?

**Comment by Claire-serveth** [comment] 2024-08-05 14:21
The ticket might be closed already as I can't seem to find it on snoozed bucket. Closing this issue now and will reopen should the issue still persists. Thank you @liliya-soroka 🙏

**Closed by Claire-serveth** 2024-08-05 14:21 UTC
